name: "Terraform configuration for MD-95.com website."

on: 
  push: 
    branches:
    - main

jobs:
  terraform: 
    name: "Terraform"
    runs-on: ubuntu-latest 

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 4.0


      - name: Configure AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> $GITHUB_ENV


     - name: Terraform Format
       id: fmt
       run terraform fmt -check

     -  name: Terraform Init
       id: init
       run terraform init

     - name: Terraform Plan
       id: plan
       run terraform plan -no-color

     - name: Terraform Apply
       run terraform apply -auto-approve